apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: mateapp
type: Opaque
stringData:
  NAME: "tododb"
  USER: "todouser"
  PASSWORD: "todopassword"
  HOST: "mysql-0.mysql-headless.mysql.svc.cluster.local"