apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
  namespace: mateapp
  labels:
    app: todolist
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todoapp-container
        # УВАГА: Твій новий зібраний образ версії 5.0.0 з підтримкою MySQL
        image: baga56789/todoapp:5.0.0
        ports:
        - name: web-port
          containerPort: 8000
        # Підключаємо всі конфіги та секрети
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "todolist.settings"
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: todoapp-configmap
              key: PYTHONUNBUFFERED
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: todoapp-secret
              key: SECRET_KEY
        # --- НОВІ ЗМІННІ ДЛЯ БД З 9-ГО ЗАВДАННЯ ---
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: HOST
        # ----------------------------------------
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/liveness/
            port: web-port
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/readiness/
            port: web-port
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: config-volume
          mountPath: /app/configs
          readOnly: true
        - name: secret-volume
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: todoapp-pvc
      - name: config-volume
        configMap:
          name: todoapp-configmap
      - name: secret-volume
        secret:
          secretName: todoapp-secret