apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS tododb;
    GRANT ALL PRIVILEGES ON tododb.* TO 'todouser'@'%';
    FLUSH PRIVILEGES;